use lumina_ai_lib::document::ShowDocumentV1;
use serde_json::{Map, Value};
use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

fn main() {
    let repository_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("src-tauri must have a repository parent")
        .to_path_buf();
    let schema_path = repository_root.join("schemas/show-document-v1.schema.json");
    let typescript_path = repository_root.join("src/generated/show-document-v1.ts");
    let schema = schemars::schema_for!(ShowDocumentV1);
    let mut contents = serde_json::to_string_pretty(&schema).expect("schema serializes");
    contents.push('\n');
    let schema_value = serde_json::to_value(&schema).expect("schema converts to JSON");
    let typescript = render_typescript(&schema_value);

    if std::env::args().any(|argument| argument == "--check") {
        let schema_is_current = fs::read_to_string(&schema_path).unwrap_or_default() == contents;
        let typescript_is_current =
            fs::read_to_string(&typescript_path).unwrap_or_default() == typescript;
        if !schema_is_current || !typescript_is_current {
            eprintln!(
                "{} is stale; run pnpm schema:generate",
                schema_path.display()
            );
            std::process::exit(1);
        }
        return;
    }

    fs::create_dir_all(schema_path.parent().expect("schema parent"))
        .expect("schema directory is writable");
    fs::write(&schema_path, contents).expect("schema artifact is writable");
    fs::create_dir_all(typescript_path.parent().expect("TypeScript parent"))
        .expect("TypeScript directory is writable");
    fs::write(&typescript_path, typescript).expect("TypeScript artifact is writable");
    println!(
        "generated {} and {}",
        schema_path.display(),
        typescript_path.display()
    );
}

fn render_typescript(schema: &Value) -> String {
    let mut output =
        String::from("// Generated by `pnpm schema:generate`. Do not edit directly.\n\n");
    let definitions = schema
        .get("$defs")
        .and_then(Value::as_object)
        .expect("schema definitions");

    for (name, definition) in definitions {
        output.push_str(&render_named_type(name, definition));
        output.push('\n');
    }
    output.push_str(&render_named_type("ShowDocumentV1", schema));
    output
}

fn render_named_type(name: &str, schema: &Value) -> String {
    if is_object_schema(schema) && schema.get("oneOf").is_none() && schema.get("anyOf").is_none() {
        format!("export interface {name} {}\n", render_object(schema, 0))
    } else {
        let rendered = render_type(schema, 0);
        let separator = if rendered.starts_with('\n') { "" } else { " " };
        format!("export type {name} ={separator}{rendered};\n")
    }
}

fn render_type(schema: &Value, indent: usize) -> String {
    if schema == &Value::Bool(true) {
        return "unknown".to_string();
    }
    if schema == &Value::Bool(false) {
        return "never".to_string();
    }
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference
            .rsplit('/')
            .next()
            .expect("reference name")
            .to_string();
    }
    if let Some(constant) = schema.get("const") {
        return serde_json::to_string(constant).expect("const serializes");
    }
    if let (Some(minimum), Some(maximum)) = (
        schema.get("minimum").and_then(Value::as_f64),
        schema.get("maximum").and_then(Value::as_f64),
    ) {
        if minimum == maximum {
            return format_number_literal(minimum);
        }
    }
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return values
            .iter()
            .map(|value| serde_json::to_string(value).expect("enum value serializes"))
            .collect::<Vec<_>>()
            .join(" | ");
    }
    for keyword in ["oneOf", "anyOf"] {
        if let Some(variants) = schema.get(keyword).and_then(Value::as_array) {
            let mut rendered = Vec::new();
            for variant in variants {
                let value = render_type(variant, indent + 4);
                if !rendered.contains(&value) {
                    rendered.push(value);
                }
            }
            if rendered.iter().any(|value| value.contains('\n'))
                || variants.iter().any(is_object_schema)
            {
                let prefix = format!("\n{}| ", " ".repeat(indent + 2));
                return format!("{prefix}{}", rendered.join(&prefix));
            }
            return rendered.join(" | ");
        }
    }

    match schema.get("type") {
        Some(Value::Array(types)) => types
            .iter()
            .filter_map(Value::as_str)
            .map(|type_name| render_type_name(type_name, schema, indent))
            .collect::<Vec<_>>()
            .join(" | "),
        Some(Value::String(type_name)) => render_type_name(type_name, schema, indent),
        _ if schema.get("properties").is_some() => render_object(schema, indent),
        _ => panic!("unsupported JSON Schema node in TypeScript generator: {schema}"),
    }
}

fn render_type_name(type_name: &str, schema: &Value, indent: usize) -> String {
    match type_name {
        "null" => "null".to_string(),
        "boolean" => "boolean".to_string(),
        "integer" | "number" => "number".to_string(),
        "string" => "string".to_string(),
        "array" => {
            if let Some(items) = schema.get("prefixItems").and_then(Value::as_array) {
                format!(
                    "[{}]",
                    items
                        .iter()
                        .map(|item| render_type(item, indent))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            } else {
                let item = schema
                    .get("items")
                    .map(|item| render_type(item, indent))
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Array<{item}>")
            }
        }
        "object" => render_object(schema, indent),
        _ => panic!("unsupported JSON Schema type in TypeScript generator: {type_name}"),
    }
}

fn render_object(schema: &Value, indent: usize) -> String {
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let required: BTreeSet<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect();
    let next_indent = indent + 2;
    let mut output = String::from("{\n");

    for (property, property_schema) in sorted_entries(&properties) {
        output.push_str(&" ".repeat(next_indent));
        output.push_str(property);
        if !required.contains(property) {
            output.push('?');
        }
        output.push_str(": ");
        output.push_str(&render_type(property_schema, next_indent));
        output.push_str(";\n");
    }
    output.push_str(&" ".repeat(indent));
    output.push('}');
    output
}

fn sorted_entries(properties: &Map<String, Value>) -> Vec<(&str, &Value)> {
    let mut entries: Vec<_> = properties
        .iter()
        .map(|(name, value)| (name.as_str(), value))
        .collect();
    entries.sort_by_key(|(name, _)| *name);
    entries
}

fn is_object_schema(schema: &Value) -> bool {
    matches!(schema.get("type"), Some(Value::String(value)) if value == "object")
        || schema.get("properties").is_some()
}

fn format_number_literal(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{}", value as i64)
    } else {
        value.to_string()
    }
}
